# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/3.2.0/reference/html/application-properties.html#application-properties
# ===================================================================
luix-rpc:
    registry:
        host: localhost
        port: 2181
# ===================================================================
# Application specific properties
# ===================================================================
application:
    url:
        appServiceProviderUrl: 127.0.0.1:14001