# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.7.1/reference/html/application-properties.html#application-properties
# ===================================================================
luix:
    registries:
        0:
            host: localhost
            port: 8500
# ===================================================================
# Application specific properties
# ===================================================================