# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.5.5/reference/html/application-properties.html#application-properties
# ===================================================================
spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/${spring.application.name}
mongock:
    enabled: false
luix:
    registry:
        host: localhost
        port: 2181
# ===================================================================
# Application specific properties
# ===================================================================
