# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  luix-demo-server-app:
    image: luix-demo-server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://luix-demo-server-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=luix-demo-server
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:8080:8080
  luix-demo-server-mongodb:
    image: mongo:4.4.10
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:27017:27017
    # volumes:
    #   - ~/volumes/luix/luix-demo-server/mongodb/:/data/db/
