# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
# ===================================================================
# Application specific properties
# ===================================================================
infinity:
  registry:
    name: zookeeper
    address: localhost:2181


