# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/reference/html/appendix-application-properties.html
# ===================================================================
infinity:
    registry:
        name: zookeeper
        address: localhost:2181
    protocol:
        port: @app.rpc.port@
# ===================================================================
# Application specific properties
# ===================================================================