# ===================================================================
# Spring Boot configuration for the "test" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# https://docs.spring.io/spring-boot/docs/2.0.4.RELEASE/reference/html/common-application-properties.html
# ===================================================================
infinity:
    registry:
        host: localhost
        port: 2181
    protocol:
        port: @app.rpc.port@
# ===================================================================
# Application specific properties
# ===================================================================
